on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

name: Rust

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: rustfmt
        run: cargo fmt -- --check

  build_and_test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test (stable)
        run: cargo test --verbose
      - uses: dtolnay/rust-toolchain@beta
      - name: cargo test (beta)
        run: cargo test --verbose
      - uses: dtolnay/rust-toolchain@nightly
      - name: cargo test (nightly)
        run: cargo test --verbose
