on: [push, pull_request]

name: Rust

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      - uses: actions/checkout@v2.3.5
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: rustfmt
        run: cargo fmt -- --check

  build_and_test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      - uses: actions/checkout@v2.3.5
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
      - name: cargo test (stable)
        run: cargo test --verbose
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: beta
          override: true
      - name: cargo test (beta)
        run: cargo test --verbose
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
      - name: cargo test (nightly)
        run: cargo test --verbose
